### ISSUE TITLE
Hackathon Page

### ISSUE THREAD

**Issue by rhnvrm** [snu-breeze/breeze-website#1]
We need to design a separate page for the flagship tech event of Breeze. 
- [x] Make a new directory /hack in the repo that will hold the files of this page
- [ ] Find possible designs and survey other hackathons that have shared their design on github on slack and telegram
- [ ] Get started with writing the design.

Comment and discuss below.

**Comment by mr-karan** [comment]
Make a new branch, merge it in master later

Also we can create the hackathon page on devpost also

**Comment by ghost** [comment]
@mr-karan Can we create a page using devpost ? I had an idea that devpost just posts updates about nearby hackathons or something like that !

**Comment by mr-karan** [comment]
~~It's doable, AFAIK~~

Edit: No OT discussions here please. Use slack.
